//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegFy.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro
    {
        public int ID { get; set; }
        public string CPFCNPJ { get; set; }
        public int IDTipo { get; set; }
        public string Placa { get; set; }
        public string Endereco { get; set; }
        public string CPF { get; set; }
    }
}
